### ISSUE TITLE
functional analysis change biomart to annotables

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/Intro-to-ChIPseq#26]

**Comment by mistrm82** [comment]
or ensembldb?

**Comment by rkhetani** [comment]
This bug seems irrelevant to the short course, but will need to be fixed for the long course. @mistrm82  am I missing something? The only mention of biomart is in https://github.com/hbctraining/Intro-to-ChIPseq/blob/master/lessons/ChIPseeker_functional_analysis.md which we are not covering in the July workshop.

**Comment by mistrm82** [comment]
@rkhetani you are right, no need to address this for the short course

**Comment by mistrm82** [comment]
keeping the issue open so it does get fixed eventually

**Comment by mistrm82** [comment]
changed it to annotationHub
